from .MaterialMain         import OBJECT_PT_GFSToolsMaterialPanel
from .ToonShadingAttribute import OBJECT_PT_GFSToolsMaterialToonShadingAttributePanel
from .Attribute1           import OBJECT_PT_GFSToolsMaterialAttributeType1Panel
from .OutlineAttribute     import OBJECT_PT_GFSToolsMaterialOutlineAttributePanel
from .Attribute3           import OBJECT_PT_GFSToolsMaterialAttributeType3Panel
from .Attribute4           import OBJECT_PT_GFSToolsMaterialAttributeType4Panel
from .Attribute5           import OBJECT_PT_GFSToolsMaterialAttributeType5Panel
from .Attribute6           import OBJECT_PT_GFSToolsMaterialAttributeType6Panel
from .Attribute7           import OBJECT_PT_GFSToolsMaterialAttributeType7Panel
